services:
  - type: web
    name: arduino-remoto
    env: node
    plan: free
    region: ohio
    buildCommand: 'cd server && npm install && node install-cli.js'
    startCommand: 'cd server && node server.js'
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: BASIC_AUTH_USER
        value: admin
      - key: BASIC_AUTH_PASS
        generateValue: true
